#! /bin/sh
set -x

which glibtoolize 2>&1 >/dev/null
if [ $? -eq 0 ]; then
  LIBTOOLIZE="glibtoolize"
else
  LIBTOOLIZE="libtoolize"
fi

$LIBTOOLIZE --force --copy
aclocal
autoheader
#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --force --copy --include-deps
automake --add-missing --force --copy
autoconf
rm -f config.cache
